import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const cliPath = join(repoRoot, 'bin', 'ai-pm-dev.mjs');

function runCli(args, options = {}) {
  return execFileSync(process.execPath, [cliPath, ...args], {
    cwd: repoRoot,
    encoding: 'utf8',
    input: options.input ?? '',
    stdio: ['pipe', 'pipe', 'pipe'],
    env: {
      ...process.env,
      AI_PM_DEV_FIXED_TIME: '2026-06-09T10:00:00.000Z',
    },
  });
}

function prdInput() {
  return `${[
    'AI fitness logging tool',
    'Fitness beginners',
    'They cannot tell whether training improves',
    'Scattered notes',
    'Log workout, review progress, receive AI summary',
    'Workout logging; progress trend; weekly summary',
    'Workout logging',
    'No social features in v1; no medical advice',
    'Sets, reps, weight',
    'Volume must be deterministic',
    'AI only summarizes',
    'Show the workouts used',
    'Protect health data',
    'A beginner understands weekly progress within five minutes',
  ].join('\n')}\n`;
}

function validPlanInput(extra = {}) {
  return `${JSON.stringify({
    goal: 'Build the smallest fitness logging MVP',
    constraints: ['Keep AI inside summaries'],
    currentState: ['PRD complete'],
    technicalApproach: 'Use deterministic workout calculations and the existing app shell.',
    slices: [
      {
        id: 'slice-1',
        title: 'Workout logging',
        mappedMustHaves: ['Workout logging'],
        provesOneThing: 'Workout logging',
        summary: 'Create the entry-to-value logging path.',
        plannedFiles: ['src/app.ts', 'src/workouts.ts'],
        verification: 'npm test and manual workout logging smoke',
        humanDecisions: ['Confirm logged workout fields'],
        docsUpdates: ['docs/dev-plan.md'],
        risks: ['Protect health data'],
      },
      {
        id: 'slice-2',
        title: 'Progress trend and weekly summary',
        mappedMustHaves: ['progress trend', 'weekly summary'],
        provesOneThing: 'Workout logging remains the anchor',
        summary: 'Add the remaining PRD must-haves after logging works.',
        plannedFiles: ['src/summary.ts'],
        verification: 'npm test summary',
        humanDecisions: [],
        docsUpdates: [],
        risks: [],
      },
    ],
    excludedNonGoals: ['No social features in v1', 'no medical advice'],
    openQuestions: [],
    ...extra,
  })}\n`;
}

const tempRoots = [];

try {
  {
    const target = mkdtempSync(join(tmpdir(), 'ai-pm-dev-plan-happy-'));
    tempRoots.push(target);
    runCli(['prd', '--target', target], { input: prdInput() });
    const sessionPath = JSON.parse(readFileSync(join(target, '.ai-pm-dev', 'state.json'), 'utf8')).prdSessionPath;

    const prdCheck = runCli(['prd', 'check', '--target', target]);
    assert.match(prdCheck, /PRD Quality Check/);
    const prdReport = readFileSync(join(sessionPath, 'quality-report.md'), 'utf8');
    assert.equal(prdReport.split('\n')[0], '# PRD Quality Report: AI fitness logging tool');
    assert.match(prdReport, /^Generated by `ai-pm-dev prd check`\.$/m);
    const prdReportJson = JSON.parse(readFileSync(join(sessionPath, 'quality-report.json'), 'utf8'));
    assert.equal(prdReportJson.generatedBy, 'ai-pm-dev prd check');

    const materialize = runCli(['plan', 'materialize', '--target', target], { input: validPlanInput() });
    assert.match(materialize, /Dev plan materialized/);
    assert.equal(existsSync(join(sessionPath, 'dev-plan.json')), true);
    assert.equal(existsSync(join(sessionPath, 'dev-plan.md')), true);
    assert.equal(existsSync(join(sessionPath, 'handoff-build.md')), true);
    assert.equal(existsSync(join(target, 'docs', 'dev-plan.md')), true);

    const plan = JSON.parse(readFileSync(join(sessionPath, 'dev-plan.json'), 'utf8'));
    assert.equal(plan.prdSessionPath, sessionPath);
    assert.equal(plan.idea, 'AI fitness logging tool');
    assert.deepEqual(plan.mustHaves, ['Workout logging', 'progress trend', 'weekly summary']);
    assert.deepEqual(plan.nonGoals, ['No social features in v1', 'no medical advice']);

    const handoff = readFileSync(join(sessionPath, 'handoff-build.md'), 'utf8');
    assert.equal(readFileSync(join(target, 'memory', 'current-task-prompt.md'), 'utf8'), handoff);
    const handoffStdout = runCli(['plan', 'handoff', '--target', target]);
    assert.equal(handoffStdout, handoff);

    const state = JSON.parse(readFileSync(join(target, '.ai-pm-dev', 'state.json'), 'utf8'));
    assert.equal(state.skill, 'dev-planner');
    assert.equal(state.phase, 'Dev Plan');
    assert.equal(state.prdSessionPath, sessionPath);

    const timeline = runCli(['timeline', '--target', target]);
    assert.match(timeline, /prd/);
    assert.match(timeline, /plan/);

    const planCheck = runCli(['plan', 'check', '--strict', '--target', target]);
    assert.match(planCheck, /Dev Plan Quality Check \(strict\)/);
    assert.match(planCheck, /Overall: PASS/);
    const planReport = readFileSync(join(sessionPath, 'dev-plan-quality-report.md'), 'utf8');
    assert.equal(planReport.split('\n')[0], '# Dev Plan Quality Report: AI fitness logging tool');
    assert.match(planReport, /^Generated by `ai-pm-dev plan check`\.$/m);
    const planReportJson = JSON.parse(readFileSync(join(sessionPath, 'dev-plan-quality-report.json'), 'utf8'));
    assert.equal(planReportJson.generatedBy, 'ai-pm-dev plan check');
  }

  {
    const target = mkdtempSync(join(tmpdir(), 'ai-pm-dev-plan-structure-'));
    tempRoots.push(target);
    runCli(['prd', '--target', target], { input: prdInput() });
    const sessionPath = JSON.parse(readFileSync(join(target, '.ai-pm-dev', 'state.json'), 'utf8')).prdSessionPath;

    let failed = false;
    let stderr = '';
    try {
      runCli(['plan', 'materialize', '--target', target], { input: '{"goal":"Broken","slices":[]}\n' });
    } catch (error) {
      failed = true;
      stderr = error.stderr || '';
    }
    assert.equal(failed, true, 'materialize should fail through the main catch on bad structure');
    assert.match(stderr, /Invalid dev plan structure/);
    assert.equal(existsSync(join(sessionPath, 'dev-plan.json')), false);
    assert.equal(existsSync(join(sessionPath, 'dev-plan.md')), false);
    assert.equal(existsSync(join(sessionPath, 'handoff-build.md')), false);
  }

  {
    const target = mkdtempSync(join(tmpdir(), 'ai-pm-dev-plan-content-'));
    tempRoots.push(target);
    runCli(['prd', '--target', target], { input: prdInput() });
    const sessionPath = JSON.parse(readFileSync(join(target, '.ai-pm-dev', 'state.json'), 'utf8')).prdSessionPath;
    runCli(['plan', 'materialize', '--target', target], {
      input: validPlanInput({
        slices: [
          {
            id: 'slice-1',
            title: 'Too broad',
            mappedMustHaves: ['Workout logging'],
            provesOneThing: '',
            summary: 'Incomplete plan.',
            plannedFiles: ['a', 'b', 'c', 'd', 'e', 'f'],
            verification: '',
            humanDecisions: [],
            docsUpdates: [],
            risks: [],
          },
        ],
        excludedNonGoals: [],
      }),
    });

    let failed = false;
    let stdout = '';
    try {
      runCli(['plan', 'check', '--strict', '--target', target]);
    } catch (error) {
      failed = true;
      stdout = error.stdout || '';
    }
    assert.equal(failed, true, 'plan check --strict should fail when required checks fail');
    assert.match(stdout, /FAIL First slice proves the one thing/);
    assert.match(stdout, /FAIL Every PRD must-have maps to a slice/);
    assert.match(stdout, /Strict mode: exiting non-zero because required checks failed/);
    assert.equal(existsSync(join(sessionPath, 'dev-plan-quality-report.md')), true);
    assert.equal(existsSync(join(sessionPath, 'dev-plan-quality-report.json')), true);
  }
} finally {
  for (const root of tempRoots) {
    rmSync(root, { recursive: true, force: true });
  }
}
