export function buildQualityReportMarkdown(answers, checks, score) {
  const row = (check) => {
    const status = check.pass ? 'PASS' : (check.severity === 'required' ? 'FAIL' : 'WARN');
    return `| ${status} | ${check.severity} | ${check.name} | ${check.pass ? '' : check.hint} |`;
  };
  return `# PRD Quality Report: ${answers.idea || 'Untitled'}

Overall: ${score.overall} (required ${score.requiredPass}/${score.requiredTotal}, recommended ${score.recommendedPass}/${score.recommendedTotal})

| Status | Severity | Check | Fix |
| --- | --- | --- | --- |
${checks.map(row).join('\n')}

Generated by \`ai-pm-dev prd check\`.
`;
}

export function qualityGateResult(checks, score) {
  return {
    overall: score.overall,
    requiredPass: score.requiredPass,
    requiredTotal: score.requiredTotal,
    recommendedPass: score.recommendedPass,
    recommendedTotal: score.recommendedTotal,
    checks: checks.map((check) => ({
      status: check.pass ? 'PASS' : (check.severity === 'required' ? 'FAIL' : 'WARN'),
      severity: check.severity,
      name: check.name,
      fix: check.pass ? '' : check.hint,
    })),
  };
}

export function buildQualityReportJson(answers, checks, score, meta = {}) {
  return {
    generatedBy: 'ai-pm-dev prd check',
    idea: answers.idea || '',
    ...meta,
    ...qualityGateResult(checks, score),
  };
}
